### ISSUE TITLE
Example file opens, but doesn't seem to be able to load webpage

### ISSUE THREAD

**Issue by songcarver** [shc-vj/SHCWebView#1]
Thanks for understanding this from a barely-a-dev question…

Seems that the demo project builds and runs, but the result doesn't seem to be able to load web content. (ie, hitting Return after a url in the search field does nothing)
![screen shot 2018-01-30 at 10 33 26 am](https://user-images.githubusercontent.com/420346/35541934-099f84a8-05a9-11e8-9c9c-1296b05ca6f4.png)
High Sierra 10.13.2

Here's to hoping for a simple fix…

**Comment by shc-vj** [comment]
Hello!

I've just updated `NSAppTransportSecurity` setting in the example project, so any URL can be viewed, not only HTTPS.

**Comment by songcarver** [comment]
W00t! Works for me! Many thanks!
